SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS userdb;
DROP TABLE IF EXISTS surveydb;
DROP TABLE IF EXISTS questiondb;
DROP TABLE IF EXISTS question_responsedb;
DROP TABLE IF EXISTS survey_questiondb;
DROP TABLE IF EXISTS survey_responsedb;
DROP TABLE IF EXISTS tagdb;
DROP TABLE IF EXISTS categorydb;
DROP TABLE IF EXISTS emdb;
DROP TABLE IF EXISTS em_tagdb;
DROP TABLE IF EXISTS em_categorydb;
SET FOREIGN_KEY_CHECKS = 1;

